import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Web3 from "web3";

import { useMoralisCloudFunction, useMoralisQuery } from "react-moralis";
import { Moralis } from "moralis";
import { encrypt } from "../utilities/helper";
import StepOne from "../components/stepOne/stepOne";
import StepTwo from "../components/stepTwo/stepTwo";
import StepThree from "../components/stepThree/stepThree";

export default function Home() {
  const [address, setAddress] = useState("");
  const [publicKey, setPublicKey] = useState("");
  const [privateKey, setPrivateKey] = useState("");
  const [message, setMessage] = useState("");

  const [pickerItems, setPickerItems] = useState([]);
  const [selectedItems, setSelectedItems] = useState([]);

  const [messages, setMessages] = useState([]);
  const [newMessages, setNewMessages] = useState([]);

  const [web3, setWeb3] = useState(null);

  useEffect(async () => {
    const web3 = new Web3(Moralis.provider);
    setWeb3(web3);

    const localUser = localStorage.getItem("user");
    if (localUser) {
      const { address, publicKey, privateKey } = JSON.parse(localUser);
      setAddress(address);
      setPublicKey(publicKey);
      setPrivateKey(privateKey);
    }
  }, []);

  const sendMessage = () => {
    const newMessages = Promise.all(
      selectedItems.map(async (wallet) => {
        const encryptedMessage = await encrypt(
          message,
          wallet.value,
          privateKey
        );
        return {
          from: address,
          to: wallet.label,
          message: encryptedMessage,
        };
      })
    );
    newMessages.then((messages) => {
      setNewMessages(messages);
      setMessage("");
      setSelectedItems([]);
    });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <StepOne
            privateKey={privateKey}
            publicKey={publicKey}
            address={address}
            setPrivateKey={setPrivateKey}
            setPublicKey={setPublicKey}
            setAddress={setAddress}
            web3={web3}
          />
        </>

        <>
          <StepTwo
            pickerItems={pickerItems}
            selectedItems={selectedItems}
            message={message}
            setMessage={setMessage}
            sendMessage={sendMessage}
            setPickerItems={setPickerItems}
            setSelectedItems={setSelectedItems}
            newMessages={newMessages}
            setNewMessages={setNewMessages}
          />
        </>
        <>
          <StepThree
            messages={messages}
            setMessages={setMessages}
            address={address}
            privateKey={privateKey}
          />
        </>
      </main>
    </div>
  );
}
